- ADAM-FURTAK/ProjectManagerApp/.gitattributes
- ADAM-FURTAK/ProjectManagerApp/.gitignore
- ADAM-FURTAK/ProjectManagerApp/.mvn/wrapper/maven-wrapper.properties
- ADAM-FURTAK/ProjectManagerApp/mvnw
- ADAM-FURTAK/ProjectManagerApp/mvnw.cmd
- ADAM-FURTAK/ProjectManagerApp/pom.xml
- ADAM-FURTAK/ProjectManagerApp/src/main/java/com/furtak/ProjectManagerApp/ProjectManagerAppApplication.java
- ADAM-FURTAK/ProjectManagerApp/src/main/java/com/furtak/ProjectManagerApp/entity/Project.java
- ADAM-FURTAK/ProjectManagerApp/src/main/java/com/furtak/ProjectManagerApp/repository/ProjectRepository.java
- ADAM-FURTAK/ProjectManagerApp/src/main/resources/application.properties
- ADAM-FURTAK/ProjectManagerApp/src/test/java/com/furtak/ProjectManagerApp/ProjectManagerAppApplicationTests.java
- ADAM-FURTAK/README.md
- add db connection
- create project table
> Adam Furtak lab 1

- Wojciech-Kapala/ProjectManagerApp/.gitattributes
- Wojciech-Kapala/ProjectManagerApp/.gitignore
- Wojciech-Kapala/ProjectManagerApp/.mvn/wrapper/maven-wrapper.properties
- Wojciech-Kapala/ProjectManagerApp/mvnw
- Wojciech-Kapala/ProjectManagerApp/mvnw.cmd
- Wojciech-Kapala/ProjectManagerApp/pom.xml
- Wojciech-Kapala/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/ProjectManagerAppApplication.java
- Wojciech-Kapala/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/Project.java
- Wojciech-Kapala/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/repository/ProjectRepository.java
- Wojciech-Kapala/ProjectManagerApp/src/main/resources/application.properties
- Wojciech-Kapala/ProjectManagerApp/src/test/java/org/example/projectmanagerapp/ProjectManagerAppApplicationTests.java
- Wojciech-Kapala/README.md
Szanowna Pani,
przepraszam za jednodniowe opóźnienie w odesłaniu laboratorium nr.1. Jest ono spowodowane wyjazdem służbowym, na którym byłem od dnia 10.03 do 13.03. W tym czasie miałem ograniczony dostęp do prywatnego komputera
- Dodano encję Project
- Dodano repozytorium JPA
- Skonfigurowano Hibernate i PostgreSQL
- Aplikacja poprawnie uruchamia się i tworzy tabelę `project`
- Logi aplikacji pokazują, że tabela została utworzona
- Potwierdzenie w PostgreSQL `\dt`
Proszę o zatwierdzenie PR.
Z wyrazami szacunku,
Wojciech Kapała
> Wojciech Kapala Lab 1

- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/.gitattributes
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/.gitignore
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/.mvn/wrapper/maven-wrapper.properties
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/mvnw
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/mvnw.cmd
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/pom.xml
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/ProjectManagerAppApplication.java
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/Project.java
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/repository/ProjectRepository.java
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/src/main/resources/application.properties
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/src/test/java/org/example/projectmanagerapp/ProjectManagerAppApplicationTests.java
- ARKADIUSZ-DOMŻAŁ/README.md
> Arkadiusz Domżał lab1

- REMIGIUSZ-GAWENDA/.gitattributes
- REMIGIUSZ-GAWENDA/.gitignore
- REMIGIUSZ-GAWENDA/.mvn/wrapper/maven-wrapper.properties
- REMIGIUSZ-GAWENDA/README.md
- REMIGIUSZ-GAWENDA/mvnw
- REMIGIUSZ-GAWENDA/mvnw.cmd
- REMIGIUSZ-GAWENDA/pom.xml
- REMIGIUSZ-GAWENDA/src/main/java/org/controller/ProjectController.java
- REMIGIUSZ-GAWENDA/src/main/java/org/example/projectmanagerapp/ProjectManagerAppApplication.java
- REMIGIUSZ-GAWENDA/src/main/java/org/example/projectmanagerapp/entity/Project.java
- REMIGIUSZ-GAWENDA/src/main/java/org/example/projectmanagerapp/repository/ProjectRepository.java
- REMIGIUSZ-GAWENDA/src/main/resources/application.properties
- REMIGIUSZ-GAWENDA/src/test/java/org/example/projectmanagerapp/ProjectManagerAppApplicationTests.java
Wykonano zadania z laboratorium nr 1.
> Laboratoria nr 1

- JAKUB-SOSNOWSKI/.idea/.gitignore
- JAKUB-SOSNOWSKI/.idea/JAKUB-SOSNOWSKI.iml
- JAKUB-SOSNOWSKI/.idea/compiler.xml
- JAKUB-SOSNOWSKI/.idea/encodings.xml
- JAKUB-SOSNOWSKI/.idea/jarRepositories.xml
- JAKUB-SOSNOWSKI/.idea/misc.xml
- JAKUB-SOSNOWSKI/.idea/modules.xml
- JAKUB-SOSNOWSKI/.idea/vcs.xml
- JAKUB-SOSNOWSKI/ProjectManagerApp/.gitattributes
- JAKUB-SOSNOWSKI/ProjectManagerApp/.gitignore
- JAKUB-SOSNOWSKI/ProjectManagerApp/.mvn/wrapper/maven-wrapper.properties
- JAKUB-SOSNOWSKI/ProjectManagerApp/mvnw
- JAKUB-SOSNOWSKI/ProjectManagerApp/mvnw.cmd
- JAKUB-SOSNOWSKI/ProjectManagerApp/pom.xml
- JAKUB-SOSNOWSKI/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/ProjectManagerAppApplication.java
- JAKUB-SOSNOWSKI/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/Project.java
- JAKUB-SOSNOWSKI/ProjectManagerApp/src/main/resources/application.properties
- JAKUB-SOSNOWSKI/ProjectManagerApp/src/test/java/org/example/projectmanagerapp/ProjectManagerAppApplicationTests.java
- JAKUB-SOSNOWSKI/README.md
- README.md
https://github.com/JakubSosnowski737/JAVA-NST-2024-2025/tree/Jakub-Sosnowski-lab1-151935
> Zadanie lab 1 skończone

- Daniel-Ryz/.idea/.gitignore
- Daniel-Ryz/.idea/Daniel-Ryz.iml
- Daniel-Ryz/.idea/compiler.xml
- Daniel-Ryz/.idea/encodings.xml
- Daniel-Ryz/.idea/jarRepositories.xml
- Daniel-Ryz/.idea/misc.xml
- Daniel-Ryz/.idea/modules.xml
- Daniel-Ryz/.idea/vcs.xml
- Daniel-Ryz/ProjectManagerApp/.gitattributes
- Daniel-Ryz/ProjectManagerApp/.gitignore
- Daniel-Ryz/ProjectManagerApp/.mvn/wrapper/maven-wrapper.properties
- Daniel-Ryz/ProjectManagerApp/mvnw
- Daniel-Ryz/ProjectManagerApp/mvnw.cmd
- Daniel-Ryz/ProjectManagerApp/pom.xml
- Daniel-Ryz/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/ProjectManagerAppApplication.java
- Daniel-Ryz/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/Project.java
- Daniel-Ryz/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/repository/ProjectRepository.java
- Daniel-Ryz/ProjectManagerApp/src/main/resources/application.properties
- Daniel-Ryz/ProjectManagerApp/src/test/java/org/example/projectmanagerapp/ProjectManagerAppApplicationTests.java
- Daniel-Ryz/README.md
Dodałem wszystko w jednym commicie, ponieważ musiałem forkować jeszcze raz.
> Daniel Ryż lab 1

- PATRYCJA-NOWAKOWSKA/ProjectManagerApp/.gitattributes
- PATRYCJA-NOWAKOWSKA/ProjectManagerApp/.gitignore
- PATRYCJA-NOWAKOWSKA/ProjectManagerApp/.mvn/wrapper/maven-wrapper.properties
- PATRYCJA-NOWAKOWSKA/ProjectManagerApp/mvnw
- PATRYCJA-NOWAKOWSKA/ProjectManagerApp/mvnw.cmd
- PATRYCJA-NOWAKOWSKA/ProjectManagerApp/pom.xml
- PATRYCJA-NOWAKOWSKA/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/ProjectManagerAppApplication.java
- PATRYCJA-NOWAKOWSKA/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/Project.java
- PATRYCJA-NOWAKOWSKA/ProjectManagerApp/src/main/resources/application.properties
- PATRYCJA-NOWAKOWSKA/ProjectManagerApp/src/test/java/org/example/projectmanagerapp/ProjectManagerAppApplicationTests.java
- PATRYCJA-NOWAKOWSKA/README.md
Utworzenie folderu Imie-Nazwisko oraz utworzenie tabeli task_manager.
> Patrycja nowakowska lab 1

- MICHAL-KOWAL/ProjectManagerApp/pom.xml
- MICHAL-KOWAL/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/controller/ProjectController.java
- MICHAL-KOWAL/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/controller/TaskController.java
- MICHAL-KOWAL/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/controller/UserController.java
- MICHAL-KOWAL/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/HighPriority.java
- MICHAL-KOWAL/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/LowPriority.java
- MICHAL-KOWAL/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/MediumPriority.java
- MICHAL-KOWAL/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/PriorityLevel.java
- MICHAL-KOWAL/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/Project.java
- MICHAL-KOWAL/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/Task.java
- MICHAL-KOWAL/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/User.java
- MICHAL-KOWAL/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/repository/ProjectRepository.java
- MICHAL-KOWAL/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/repository/TaskRepository.java
- MICHAL-KOWAL/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/repository/UserRepository.java
> Michal kowal 2

- Mateusz-Więcek/.gitattributes
- Mateusz-Więcek/.gitignore
- Mateusz-Więcek/.mvn/wrapper/maven-wrapper.properties
- Mateusz-Więcek/mvnw
- Mateusz-Więcek/mvnw.cmd
- Mateusz-Więcek/pom.xml
- Mateusz-Więcek/src/main/java/org/example/projectmanagerapp/ProjectManagerAppApplication.java
- Mateusz-Więcek/src/main/java/org/example/projectmanagerapp/ProjectRepository.java
- Mateusz-Więcek/src/main/java/org/example/projectmanagerapp/UserRepository.java
- Mateusz-Więcek/src/main/java/org/example/projectmanagerapp/controller/ProjectController.java
- Mateusz-Więcek/src/main/java/org/example/projectmanagerapp/controller/TaskController.java
- Mateusz-Więcek/src/main/java/org/example/projectmanagerapp/controller/UserController.java
- Mateusz-Więcek/src/main/java/org/example/projectmanagerapp/entity/Project.java
- Mateusz-Więcek/src/main/java/org/example/projectmanagerapp/entity/Task.java
- Mateusz-Więcek/src/main/java/org/example/projectmanagerapp/entity/TaskType.java
- Mateusz-Więcek/src/main/java/org/example/projectmanagerapp/entity/User.java
- Mateusz-Więcek/src/main/java/org/example/projectmanagerapp/enums/HighPriority.java
- Mateusz-Więcek/src/main/java/org/example/projectmanagerapp/enums/LowPriority.java
- Mateusz-Więcek/src/main/java/org/example/projectmanagerapp/enums/MediumPriority.java
- Mateusz-Więcek/src/main/java/org/example/projectmanagerapp/repository/ProjectRepository.java
- Mateusz-Więcek/src/main/java/org/example/projectmanagerapp/repository/TaskRepository.java
- Mateusz-Więcek/src/main/java/org/example/projectmanagerapp/repository/UserRepository.java
- Mateusz-Więcek/src/main/resources/application.properties
- Mateusz-Więcek/src/test/java/org/example/projectmanagerapp/ProjectManagerAppApplicationTests.java
Added entities, repositories, and REST controllers for Task, User, and Project.
Implemented dynamic task priority handling using polymorphism.
> Mateusz wiecek lab2

- LUKASZ-ZAREBA/ProjectManagerApp/pom.xml
- LUKASZ-ZAREBA/ProjectManagerApp/src/main/java/com/example/projectmanagerapp/controller/ProjectController.java
- LUKASZ-ZAREBA/ProjectManagerApp/src/main/java/com/example/projectmanagerapp/controller/TaskController.java
- LUKASZ-ZAREBA/ProjectManagerApp/src/main/java/com/example/projectmanagerapp/controller/UserController.java
- LUKASZ-ZAREBA/ProjectManagerApp/src/main/java/com/example/projectmanagerapp/entity/Projects.java
- LUKASZ-ZAREBA/ProjectManagerApp/src/main/java/com/example/projectmanagerapp/entity/Task.java
- LUKASZ-ZAREBA/ProjectManagerApp/src/main/java/com/example/projectmanagerapp/entity/User.java
- LUKASZ-ZAREBA/ProjectManagerApp/src/main/java/com/example/projectmanagerapp/entity/task_type.java
- LUKASZ-ZAREBA/ProjectManagerApp/src/main/java/com/example/projectmanagerapp/priority/HighPriority.java
- LUKASZ-ZAREBA/ProjectManagerApp/src/main/java/com/example/projectmanagerapp/priority/LowPriority.java
- LUKASZ-ZAREBA/ProjectManagerApp/src/main/java/com/example/projectmanagerapp/priority/MediumPriority.java
- LUKASZ-ZAREBA/ProjectManagerApp/src/main/java/com/example/projectmanagerapp/priority/PriorityLevel.java
- LUKASZ-ZAREBA/ProjectManagerApp/src/main/java/com/example/projectmanagerapp/repository/TaskRepository.java
- LUKASZ-ZAREBA/ProjectManagerApp/src/main/java/com/example/projectmanagerapp/repository/UserRepository.java
Implementation of JPA entities for users, projects, and tasks with dynamic task priorities. Created REST API controllers.
> Lukasz zareba lab02

- Wojciech-Kapala/ProjectManagerApp/pom.xml
- Wojciech-Kapala/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/ProjectManagerAppApplication.java
- Wojciech-Kapala/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/controller/ProjectController.java
- Wojciech-Kapala/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/controller/TaskController.java
- Wojciech-Kapala/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/controller/UserController.java
- Wojciech-Kapala/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/Project.java
- Wojciech-Kapala/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/Task.java
- Wojciech-Kapala/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/User.java
- Wojciech-Kapala/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/priority/PriorityLevel.java
- Wojciech-Kapala/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/priority/TaskPriority.java
- Wojciech-Kapala/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/repository/TaskRepository.java
- Wojciech-Kapala/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/repository/UserRepository.java
- Wojciech-Kapala/ProjectManagerApp/src/main/resources/application.properties
Zrealizowano Lab2 zgodnie z wytycznymi.
✔️ Utworzone encje: User, Project, Task
✔️ Repozytoria i kontrolery REST (GET/POST)
✔️ Priorytety zrealizowane przez enum TaskPriority implementujący interfejs PriorityLevel
✔️ Testowane lokalnie + PostgreSQL + Postman
✔️ JSON serializacja poprawiona przy użyciu @JsonManagedReference / @JsonBackReference
> Wojciech Kapała Lab2: Dodano encje, kontrolery REST, priorytety z polimorfizmem (ENUM)

- BARTLOMIEJ-KOT/ProjectManagerApp/pom.xml
- BARTLOMIEJ-KOT/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/ProjectManagerAppApplication.java
- BARTLOMIEJ-KOT/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/controller/ProjectController.java
- BARTLOMIEJ-KOT/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/controller/TaskController.java
- BARTLOMIEJ-KOT/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/controller/UserController.java
- BARTLOMIEJ-KOT/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/ProjectUser.java
- BARTLOMIEJ-KOT/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/Task.java
- BARTLOMIEJ-KOT/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/TaskPriority.java
- BARTLOMIEJ-KOT/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/User.java
- BARTLOMIEJ-KOT/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/priority/HighPriority.java
- BARTLOMIEJ-KOT/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/priority/LowPriority.java
- BARTLOMIEJ-KOT/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/priority/MediumPriority.java
- BARTLOMIEJ-KOT/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/priority/PriorityLevel.java
- BARTLOMIEJ-KOT/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/repository/ProjectRepository.java
- BARTLOMIEJ-KOT/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/repository/TaskRepository.java
- BARTLOMIEJ-KOT/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/repository/UserRepository.java
- BARTLOMIEJ-KOT/ProjectManagerApp/src/main/resources/application.properties
Niestety nie przy każdym commicie zrobiłem add. Wyrównałem to ostatnim commitem, który jest troszkę obszerniejszy.
> Bartlomiej kot lab 2

- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/pom.xml
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/controller/ProjectsController.java
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/controller/TasksController.java
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/controller/UsersController.java
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/HighPriority.java
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/LowPriority.java
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/MediumPriority.java
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/PriorityLevel.java
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/Projects.java
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/Tasks.java
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/Users.java
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/repository/ProjectRepository.java
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/repository/TaskRepository.java
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/repository/UserRepository.java
- ARKADIUSZ-DOMŻAŁ/ProjectManagerApp/src/main/resources/application.properties
> Arkadiusz Domżał 2 lab

- .idea/.gitignore
- .idea/JAVA-NST-2024-2025.iml
- .idea/compiler.xml
- .idea/encodings.xml
- .idea/jarRepositories.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- Nina Kowalczuk/.idea/.gitignore
- Nina Kowalczuk/.idea/Nina Kowalczuk.iml
- Nina Kowalczuk/.idea/misc.xml
- Nina Kowalczuk/.idea/modules.xml
- Nina Kowalczuk/.idea/vcs.xml
- Nina Kowalczuk/ProjectManagerApp/.gitattributes
- Nina Kowalczuk/ProjectManagerApp/.gitignore
- Nina Kowalczuk/ProjectManagerApp/.mvn/wrapper/maven-wrapper.properties
- Nina Kowalczuk/ProjectManagerApp/mvnw
- Nina Kowalczuk/ProjectManagerApp/mvnw.cmd
- Nina Kowalczuk/ProjectManagerApp/pom.xml
- Nina Kowalczuk/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/ProjectManagerAppApplication.java
- Nina Kowalczuk/ProjectManagerApp/src/main/resources/application.properties
- Nina Kowalczuk/ProjectManagerApp/src/test/java/org/example/projectmanagerapp/ProjectManagerAppApplicationTests.java
- Nina Kowalczuk/README.md
Dodano encję Project, skonfigurowano bazę danych
> Nina kowalczuk

- MICHAL-KOWAL/ProjectManagerApp/pom.xml
- MICHAL-KOWAL/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/controller/ProjectController.java
- MICHAL-KOWAL/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/controller/TaskController.java
- MICHAL-KOWAL/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/controller/UserController.java
- MICHAL-KOWAL/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/service/ProjectService.java
- MICHAL-KOWAL/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/service/TaskService.java
- MICHAL-KOWAL/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/service/UserService.java
- MICHAL-KOWAL/ProjectManagerApp/src/test/java/ProjectControllerTest.java
- MICHAL-KOWAL/ProjectManagerApp/src/test/java/ProjectServiceTest.java
- MICHAL-KOWAL/ProjectManagerApp/src/test/java/TaskControllerTest.java
- MICHAL-KOWAL/ProjectManagerApp/src/test/java/TaskServiceTest.java
- MICHAL-KOWAL/ProjectManagerApp/src/test/java/UserControllerTest.java
- MICHAL-KOWAL/ProjectManagerApp/src/test/java/UserServiceTest.java
> Michal kowal - Lab 3

- BARTLOMIEJ-SZOLDROWSKI/ProjectManagerApp/pom.xml
- BARTLOMIEJ-SZOLDROWSKI/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/controller/ProjectController.java
- BARTLOMIEJ-SZOLDROWSKI/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/controller/TaskController.java
- BARTLOMIEJ-SZOLDROWSKI/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/controller/UserController.java
- BARTLOMIEJ-SZOLDROWSKI/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/Project.java
- BARTLOMIEJ-SZOLDROWSKI/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/Task.java
- BARTLOMIEJ-SZOLDROWSKI/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/User.java
- BARTLOMIEJ-SZOLDROWSKI/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/service/ProjectService.java
- BARTLOMIEJ-SZOLDROWSKI/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/service/TaskService.java
- BARTLOMIEJ-SZOLDROWSKI/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/service/UserService.java
- BARTLOMIEJ-SZOLDROWSKI/ProjectManagerApp/src/test/java/org/example/projectmanagerapp/tests/ProjectServiceTest.java
- BARTLOMIEJ-SZOLDROWSKI/ProjectManagerApp/src/test/java/org/example/projectmanagerapp/tests/TaskServiceTest.java
- BARTLOMIEJ-SZOLDROWSKI/ProjectManagerApp/src/test/java/org/example/projectmanagerapp/tests/UserServiceTest.java
[Lab 3] API Documentation, Services Layer & Unit Tests" 
- Added Swagger/OpenAPI documentation for all endpoints
- Implemented service layer (User/Project/Task Services)
- Added CRUD operations (PUT/DELETE methods)
- Wrote comprehensive unit tests (80%+ coverage via JaCoCo)
- Separated business logic from controllers
- Applied Mockito for service layer testing
- Configured JaCoCo for Java 21 compatibility
> Bartłomiej Szołdrowski Lab3

- Bartosz-Sochacki/ProjectManagerApp/.gitattributes
- Bartosz-Sochacki/ProjectManagerApp/.gitignore
- Bartosz-Sochacki/ProjectManagerApp/.mvn/wrapper/maven-wrapper.properties
- Bartosz-Sochacki/ProjectManagerApp/mvnw
- Bartosz-Sochacki/ProjectManagerApp/mvnw.cmd
- Bartosz-Sochacki/ProjectManagerApp/pom.xml
- Bartosz-Sochacki/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/ProjectManagerAppApplication.java
- Bartosz-Sochacki/ProjectManagerApp/src/main/resources/application.properties
- Bartosz-Sochacki/ProjectManagerApp/src/test/java/org/example/projectmanagerapp/ProjectManagerAppApplicationTests.java
- Bartosz-Sochacki/README.md
Zrobiłem fork repozytorium głównego
Sklonowałem swój fork lokalnie
Utworzyłem nową gałąź Bartosz-Sochacki-lab1
Dodałem folder z moim nazwiskiem do repozytorium
Wykonałem commit i push zmian na GitHub
2. Spring Boot z Maven
Utworzyłem nowy projekt Spring Boot z nazwą ProjectManagerApp
Skonfigurowałem projekt z Maven jako system budowania
Ustaliłem wersję Java na 17 (rozwiązałem konflikty z wersjami 21/24)
Dodałem wszystkie wymagane zależności:
Spring Boot DevTools
Spring Data JPA
PostgreSQL Driver
Lombok
3. PostgreSQL i baza danych
Utworzyłem bazę danych task_manager
Skonfigurowałem użytkownika myuser z odpowiednimi uprawnieniami
Dodałem konfigurację połączenia w application.properties
Sprawdziłem, że Hibernate automatycznie tworzy tabele
> Bartosz sochacki lab1

- Oskar-Swiatek/ProjectManagerApp/pom.xml
- Oskar-Swiatek/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/controller/ProjectController.java
- Oskar-Swiatek/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/project/Project.java
- Oskar-Swiatek/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/entity/user/User.java
- Oskar-Swiatek/ProjectManagerApp/src/main/java/org/example/projectmanagerapp/service/ProjectService.java
- Oskar-Swiatek/ProjectManagerApp/src/test/java/org/example/projectmanagerapp/integration/ProjectUserIntegrationTest.java
- Oskar-Swiatek/ProjectManagerApp/src/test/java/org/example/projectmanagerapp/service/ProjectServiceTest.java
> Oskar Świątek Lab 04

- Wojciech-Kapala/ProjectManagerApp/pom.xml
- Wojciech-Kapala/ProjectManagerApp/src/test/java/org/example/projectmanagerapp/integration/ProjectIntegrationIT.java
W ramach tego laboratorium zaimplementowałem kompletne testy integracyjne dla aplikacji ProjectManagerApp, koncentrując się na testowaniu pełnego przepływu API oraz relacji między encjami.
Główne elementy implementacji:
Testy integracyjne API - pełne testowanie operacji CRUD dla projektów, zadań i użytkowników
Testowanie relacji między encjami - sprawdzanie poprawności relacji projekt-użytkownik, projekt-zadanie
Konfiguracja TestContainers - użycie kontenerów PostgreSQL do testów na realnej bazie danych
Konfiguracja JaCoCo - rozdzielenie raportów pokrycia dla testów jednostkowych i integracyjnych
Wyniki testów:
100% pokrycia kontrolerów (wszystkie endpointy API są przetestowane)
81% pokrycia warstwy serwisów
85% pokrycia klas pomocniczych
86% całkowitego pokrycia kodu testami …
> Wojciech Kapała - Lab 4: Integration Tests

- Kacper-Bukowski/ProjectManagerApp/Dockerfile
- Kacper-Bukowski/ProjectManagerApp/docker-compose.yml
- Kacper-Bukowski/ProjectManagerApp/src/main/resources/application.properties
Introduced a Dockerfile and Docker Compose setup for the Project Manager App, enabling containerized deployment with PostgreSQL. Updated `application.properties` to use environment variable overrides for database configuration. Added a detailed README to guide users in building and running the application with Docker. no longer includes the Docker build and run instructions for the Project Manager App. This streamlines the documentation and removes redundant or unnecessary deployment details.
> Add Docker support for containerized deployment

- Daniel-Ryz/.idea/compiler.xml
- Daniel-Ryz/ProjectManagerApp/Dockerfile
- Daniel-Ryz/ProjectManagerApp/src/main/resources/application.properties
- Daniel-Ryz/docker-compose.yml
Pull Request to lab-5 Daniel Ryż
> Daniel ryz lab 5
